---

# To install it manually.
# 1. Create the /etc/automysqlbackup directory.
# 2. Copy in the automysqlbackup.conf file.
# 3. Copy the automysqlbackup file to /usr/local/bin and make executable.
# 4. cp /etc/automysqlbackup/automysqlbackup.conf /etc/automysqlbackup/myserver.conf
# 5. Edit the /etc/automysqlbackup/myserver.conf file to customise your settings.

- name: Manual | Create the automysqlbackup directory
  file:
    path: "{{ automysqlbackup_folder }}"
    state: directory
    owner: "{{ automysqlbackup_user }}"
    group: "{{ automysqlbackup_group }}"
    mode: 0775
    recurse: no
  become: true
  tags: [automysqlbackup]

# on some systems the tmp mount is set to noexec
# so we have to use a different tmp folder
# https://github.com/ansible/ansible/issues/30064
- name: Manual | Create the automysqlbackup tmp directory
  file:
    path: "{{ automysqlbackup_tmp_folder }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ first5user_admin_group }}"
    mode: 0775
    recurse: no
  become: true
  tags: [automysqlbackup]
  when: automysqlbackup_tmp_folder != '/tmp'


- name: Manual | Get automysqlbackup from github
  environment:
      TMPDIR: "{{ automysqlbackup_tmp_folder }}"
      TMP: "{{ automysqlbackup_folder }}"
      TEMP: "{{ automysqlbackup_folder }}"
  git:
    repo: "{{ automysqlbackup_repo }}"
    dest: "{{ automysqlbackup_folder }}"
    version: "{{ automysqlbackup_repo_branch }}"
    accept_hostkey: "yes"
    force: no
    update: yes
  become: true
  tags: [automysqlbackup]

- name: Manual | Link the automysqlbackup file to bin
  file:
    state: link
    src: "{{ automysqlbackup_folder }}/automysqlbackup"
    dest: "{{ automysqlbackup_binpath }}"
    mode: 0750
  become: true
  tags: [automysqlbackup]

- name: Manual | Correct permissions for file
  file:
    path: "{{ automysqlbackup_folder }}/automysqlbackup"
    owner: "{{ automysqlbackup_user }}"
    group: "{{ automysqlbackup_group }}"
    mode: 0750
  become: true
  tags: [automysqlbackup]

- name: Manual | Set the configuration
  template:
    src: automysqlbackup_v3.conf.j2
    dest: "{{ automysqlbackup_folder }}/automysqlbackup.local.conf"
    backup: yes
    mode: 0640
    owner: "{{ automysqlbackup_user }}"
    group: "{{ automysqlbackup_group }}"
  no_log: true
  become: true
  tags: [automysqlbackup]


- name: set fact for health check monitoring on cron
  set_fact:
    health_chk: '&& curl -fsS --retry 3 {{ healthcheck_monitor.db_backup.url }}/{{ healthcheck_monitor.db_backup.key }}'
  when: healthcheck_monitor.db_backup.enabled


- name: set fact for health check monitoring on cron
  set_fact:
    health_chk: ''
  when: not healthcheck_monitor.db_backup.enabled


- name: Manual | Automysqlbackup daily cronjob for backup
  cron:
    name: "Automysqlbackup - Backup DB"
    hour: "{{ automysqlbackup_cron_hour }}"
    minute: "{{ automysqlbackup_cron_minute }}"
    job: "{{ automysqlbackup_binpath }} {{ health_chk }} > /dev/null"
    cron_file: automysqlbackup
    user: "{{ automysqlbackup_user }}"
    state: present
    disabled: "{{ automysqlbackup_cron_disabled }}"
  become: true
  tags: [automysqlbackup]
