---
#
# Automysql Backup: tasks file for automysqlbackup
#
# The Apt version is 2.5 - the latest version is 3
#  Creates the following folders
#
#  ./etc/automysqlbackup
#  ./etc/default/automysqlbackup - the default config
#  ./etc/cron.daily/automysqlbackup - cron job
#  ./usr/share/doc/automysqlbackup/ - readme
#  ./usr/sbin/automysqlbackup - the script itself
#  ./var/lib/automysqlbackup

- name: MySQL | automysqlbackup install
  apt:
    name: automysqlbackup
    state: installed
  sudo: true
  tags:
    - automysqlbackup

- name: MySQL | Set automysql backup cfg
  template:
    src: automysqlbackup_v2.conf.j2
    dest: /etc/default/automysqlbackup
    backup: yes
  tags:
   - automysqlbackup


- name: MySQL | cronjob for automysqlbackup each day
  cron:
    name: "Automysqlbackup - Backup DB"
    hour: "{{ automysqlbackup_cron_hour }}"
    minute: "{{ automysqlbackup_cron_minute }}"
    job: "{{ automysqlbackup_binpath }} > /dev/null"
  tags:
    - automysqlbackup